language: csharp
solution: MarcusW.SharpUtils.sln
dist: bionic
mono: none
dotnet: 2.2.105

install:
  - dotnet restore

script:
  - dotnet test
  - dotnet build -c Release

deploy:
  provider: script
  script: dotnet pack MarcusW.SharpUtils.Core/MarcusW.SharpUtils.Core.csproj -c Release && \
    dotnet pack MarcusW.SharpUtils.Gtk/MarcusW.SharpUtils.Gtk.csproj -c Release && \
    dotnet pack MarcusW.SharpUtils.Redis/MarcusW.SharpUtils.Redis.csproj -c Release && \
    find . -name '*.nupkg' -exec dotnet nuget push {} -k $NUGET_KEY -s https://nuget.org \;
  on:
    tags: true
