version: 2.1
jobs:
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run: dotnet test
  deploy:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run: dotnet pack MarcusW.SharpUtils.Core/MarcusW.SharpUtils.Core.csproj -c Release
      - run: dotnet pack MarcusW.SharpUtils.Validation/MarcusW.SharpUtils.Validation.csproj -c Release
      - run: dotnet pack MarcusW.SharpUtils.DependencyInjection/MarcusW.SharpUtils.DependencyInjection.csproj -c Release
      - run: dotnet pack MarcusW.SharpUtils.AspNetCore/MarcusW.SharpUtils.AspNetCore.csproj -c Release
      - run: dotnet pack MarcusW.SharpUtils.Gtk/MarcusW.SharpUtils.Gtk.csproj -c Release
      - run: dotnet pack MarcusW.SharpUtils.Redis/MarcusW.SharpUtils.Redis.csproj -c Release
      - deploy:
          name: Push to nuget.org
          command: find . -name '*.nupkg' -exec dotnet nuget push {} -k $NUGET_KEY -s https://nuget.org \;
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
